### ISSUE TITLE
Compilation Error in Actor Trait Implementation: Lifetime Parameters Mismatch on ractor 0.14.*, migrating from 0.13

### ISSUE THREAD

**Issue by shashwatmi** [slawlor/ractor#326]
**Describe the bug**  
In `ractor` version `0.14.6`, the implementation of the `Actor` trait's  causes a compilation error 'lifetime parameters or bounds on method `handle_supervisor_evt` do not match the trait declaration [E0195]'. This issue did not occur in `ractor` version `0.13.*`, indicating a breaking change in how the trait is defined or enforced in the new version.
I'm fairly new in Rust, might be doing something wrong, have i missed anything?
**Additional context**  
- **Rust Version**: `rustc 1.83.0 (90b35a623 2024-11-26)`  
- **Ractor Version**: `0.14.6`  
- **Other Crates Imported**: `async_trait`
- **Error Message**:  
   ```plaintext
   error[E0195]: lifetime parameters or bounds on method `handle_supervisor_evt` do not match the trait declaration
   ```
- **Code Example (Fails on 0.14.6, Working in 0.13) **:  
   ```rust
   #[async_trait::async_trait]
   impl<T: DataVendor + Send + Sync + Clone + 'static> Actor for SupervisedVendor<T> {
       type Msg = SupervisorMessage;
       type State = SupervisorState;
       type Arguments = ();


      async fn pre_start(
          &self,
          myself: ActorRef<Self::Msg>,
          args: Self::Arguments
      )  -> Result<Self::State, ActorProcessingErr> {
          myself.send_message(SupervisorMessage::SpawnVendor)?;
          Ok(SupervisorState::new())
      }

   }

**Comment by slawlor** [comment]
Add the async-trait feature to the ractor import. There was a change to not auto include it and instead rely on native async traits by default. This was to support both versions with ractor_cluster

**Comment by slawlor** [comment]
Optionally you can remove your dependence on the async-trait crate but that's a change in your logic. This isn't so much an API break rather just which are the default features mix so deemed not an API break

```lang=toml
ractor= { version = "0.14", features = ["async-trait"] }
```

**Comment by shashwatmi** [comment]
@slawlor thanks, it worked.
